### ISSUE TITLE
Tokens in web version, but nothing in api

### ISSUE THREAD

**Issue by Ololosha100501** [Uniswap/api-deprecated#11]
Hi. For example there is token AKRO (contract 0x8ab7404063ec4dbcfd4598215992dc3f8ec853d7) in web interface v1.
https://uniswap.exchange/swap?inputCurrency=ETH&outputCurrency=0x8ab7404063ec4dbcfd4598215992dc3f8ec853d7&use=v1

But there is no this token in api. 

I think it isn't normal =)

And don't know how much tokens like this one.

**Comment by moodysalem** [comment]
We only return the top 1k assets. If you want more information use the subgraph
