### ISSUE TITLE
7 hours information delay

### ISSUE THREAD

**Issue by Ololosha100501** [Uniswap/api-deprecated#12]
Trying to recieve v1 orderbook for DGX token (https://api.uniswap.info/v1/orderbook/ETH_0xb92dE8B30584392Af27726D5ce04Ef3c4e5c9924)

There is timestamp 1593090523. It was 7 hours ago. 

And as I know api should cash actual info once in 15 minutes.

**Comment by moodysalem** [comment]
could be due to a subgraph delay, but too late to debug
