### ISSUE TITLE
The trades API does not work. return zero trades

### ISSUE THREAD

**Issue by bingbinglee** [Uniswap/api-deprecated#14]
https://api.uniswap.info/v2/trades/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48_0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2

The above API is the trades for USDC_ETH pair on uniswap.
It returns zero results as of July 18, 2020.

This is true for all the other pairs as well. /orderbook/ is working fine however.

**Comment by bingbinglee** [comment]
@moodysalem

**Comment by moodysalem** [comment]
this is now working

**Comment by bingbinglee** [comment]
This has broken down again. 
Now this endpoint simply respond "forbidden".

Is there any reliable alternative to this endpoint? It's highly unusable in production if there is no stability to this.

**Comment by moodysalem** [comment]
@bingbinglee https://github.com/Uniswap/uniswap-api/blob/master/README.md
