### ISSUE TITLE
API Endpoints broken (?)

### ISSUE THREAD

**Issue by 0x53fa29jhezc** [Uniswap/api-deprecated#15]
For example for:

https://api.uniswap.info/v2/assets

I get this Error:

{"errorCode":500,"message":"GraphQL error: Failed to decode `block.number` value: `subgraph QmNPKaPqgTqKdCv2k3SF9vAhbHo4PVb2cKx2Gs4PzNQkZx has only indexed up to block number 10481165 and data for block number 10490264 is therefore not yet available`"}

**Comment by moodysalem** [comment]
@ianlapham fixed this in the subgraph
