### ISSUE TITLE
`/tickers` is returning 403 Forbidden

### ISSUE THREAD

**Issue by trestrantham** [Uniswap/api-deprecated#21]
This appears to be a recent issue/change as of today. Is this API endpoint going to be supported going forward?

**Comment by moodysalem** [comment]
See https://github.com/Uniswap/uniswap-api/blob/master/README.md#getting-an-api-key

**Comment by trestrantham** [comment]
Thanks, we've submitted a request. I assume this was a recent change? I was testing against this endpoint yesterday without issue.

**Comment by moodysalem** [comment]
Yes, deployed today, but have been notifying the discord for a couple weeks. Recommend you join the discord for future communications
