### ISSUE TITLE
API Key Request

### ISSUE THREAD

**Issue by K-NRS** [Uniswap/api-deprecated#25]
We've sent an api request 2 days ago, still waiting. Please give a response.

**Comment by taoteh1221** [comment]
I sent my request weeks ago, also never heard back, and ended up using Defipulse instead: https://data.defipulse.com Good alternative, used by coingecko...liking it so far.

**Comment by K-NRS** [comment]
> I sent my request weeks ago, also never heard back, and ended up using Defipulse instead: https://data.defipulse.com Good alternative, used by coingecko...liking it so far.

It looks like limited. I need free API key source. Do you know else?
